<?php

namespace Guy\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository {

    public function getDistinctTags() {
	return $this
			->createQueryBuilder('t')
			->orderBy('t.nom', 'ASC')
			->groupBy('t.nom')
			->getQuery()
			->getResult();
    }

}
