<?php

namespace Guy\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findWithToken($token)
	{
		return $this->findOneBySalt($token);
		// $qb = $this->_em->createQueryBuilder();
 
		// return $qb->select('u')
		// ->from('GuyUserBundle:User', 'u')
		// ->where('u.salt = :token')
		// ->setParameter('token', $token)
		// ->getQuery()
		// ->getResult();
	}
}
